syntax = "proto3";
package the_wheel.v1;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

message AddEntryEventData {
  string label = 1;
}

message RemoveEntryEventData {
  string label = 1;
}

message WheelEventData {
  oneof event_data {
    option (buf.validate.oneof).required = true;

    AddEntryEventData add_entry = 1;
    RemoveEntryEventData remove_entry = 2;
  };
}

message WheelEvent {
  string id = 1;
  google.protobuf.Timestamp created_at = 2;
  WheelEventData event_data = 3;
}
