syntax = "proto3";
package the_wheel.v1;

import "buf/validate/validate.proto";
import "google/protobuf/timestamp.proto";

message AddEntryEventData {
  string id = 1 [(buf.validate.field).string.uuid = true];
  string label = 2 [(buf.validate.field).string.min_len = 1];
}

message RemoveEntryEventData {
  string id = 1 [(buf.validate.field).string.uuid = true];
}

message WheelEventData {
  // note: this field isn't embedded directly into `WheelEvent` as we need a distinct
  //       `message` to pass into the fromBinary/toBinary [de]serialization helpers.

  oneof event_data {
    option (buf.validate.oneof).required = true;

    AddEntryEventData add_entry = 1;
    RemoveEntryEventData remove_entry = 2;
  }
}

message WheelEvent {
  // UUID v4
  string id = 1 [(buf.validate.field).string.uuid = true];
  google.protobuf.Timestamp created_at = 2;
  // Data specific to the event variant
  WheelEventData event_data = 3;
}
