name: Checks

permissions:
  pull-requests: write

on:
  pull_request:
    types:
      - opened
      - reopened
      - synchronize

jobs:
  buf:
    name: Buf
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v6
        # see https://buf.build/docs/bsr/ci-cd/github-actions/#parameters
      - uses: bufbuild/buf-action@v1
        with:
          input: proto/
